# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c64bb784bc70bd294547aa4ce1c7d84d58b67b7f8b8eac23a2223509a5f785600bc7b6bb0e02ccd01029f95ae4769f01d8d542760573aebf944d98134b1b49f

test:
  secret_key_base: 8a2f927765131e872ca465e6a0c2a99169d7a1c4f4446c964eca3fbad36812562f1de70b58d23cc6c31e781ea6fcd69a03dbb2dcce278bd555df422657fada6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
